accepted_extensions:
  - .jpg
  - .jpeg
  - .png
  - .gif
  - .bmp
  - .mp4
  - .avi
  - .mov
  - .mkv
language: en
tags_file: tags.json
tag_usage_file: tag_usage.json
last_project_number: ""
tag_panel_visible: false
