# Default configuration settings for the mic-renamer application.
# These values are used if no user-specific settings are found or if settings are reset.
# This file is bundled with the application and should not be directly modified by users.
# User-specific settings are stored in 'app_settings.yaml' in the configuration directory.
accepted_extensions:
  - .jpg
  - .jpeg
  - .png
  - .gif
  - .bmp
  - .heic
  - .mp4
  - .avi
  - .mov
  - .mkv
language: en
tags_file: tags.json
tag_usage_file: tag_usage.json
last_project_number: ""
tag_panel_visible: false
toolbar_style: icons
default_save_directory: ""
default_import_directory: ""
compression_max_size_kb: 2500
compression_quality: 99
compression_reduce_resolution: true
compression_resize_only: false
compression_max_width: 1440
compression_max_height: 1440
compress_after_rename: false