# PyInstaller spec file for Mic Renamer
# generated by Codex

block_cipher = None


from PyInstaller.utils.hooks import collect_submodules
import os

icon_file = 'favicon.ico' if os.path.exists('favicon.ico') else None

hiddenimports = collect_submodules('mic_renamer')


a = Analysis(
    ['mic_renamer/__main__.py'],
    pathex=['.'],
    binaries=[],
    datas=[('mic_renamer/config/defaults.yaml', 'mic_renamer/config'),
           ('mic_renamer/config/tags.json', 'mic_renamer/config')],
    hiddenimports=hiddenimports,
    hookspath=[],
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='mic-renamer',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    runtime_tmpdir=None,
    icon=icon_file,
)
